INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION)
SELECT 10001, 'Tony', 'Stark', 'tony.stark@gmail.com', 'Australia' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=10001 LIMIT 1);

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION)
SELECT 10002, 'Bruce', 'Banner', 'bruce.banner@gmail.com', 'US' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=10002 LIMIT 1);

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION)
SELECT 10003, 'Steve', 'Rogers', 'steve.rogers@hotmail.com', 'Australia' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=10003 LIMIT 1);

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION)
SELECT 10004, 'Wanda', 'Maximoff', 'wanda.maximoff@gmail.com', 'US' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=10004 LIMIT 1);

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION)
SELECT 10005, 'Natasha', 'Romanoff', 'natasha.romanoff@gmail.com', 'Canada' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=10005 LIMIT 1);


INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS)
SELECT 'PRODUCT_001', 50, 'Active' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_CODE='PRODUCT_001' LIMIT 1);

INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS)
SELECT 'PRODUCT_002', 100, 'Inactive' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_CODE='PRODUCT_002' LIMIT 1);

INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS)
SELECT 'PRODUCT_003', 200, 'Active' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_CODE='PRODUCT_003' LIMIT 1);

INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS)
SELECT 'PRODUCT_004', 10, 'Inactive' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_CODE='PRODUCT_004' LIMIT 1);

INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS)
SELECT 'PRODUCT_005', 500, 'Active' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_CODE='PRODUCT_005' LIMIT 1);

INSERT INTO TRANSACTION (TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_TIME, QUANTITY, PRODUCT_CODE)
SELECT 100001, 10001, now(), 1, 'PRODUCT_001' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM TRANSACTION WHERE TRANSACTION_ID=100001 LIMIT 1);