create table IF NOT EXISTS CUSTOMER(
  CUSTOMER_ID int not null AUTO_INCREMENT,
  FIRST_NAME varchar,
  LAST_NAME varchar,
  EMAIL varchar,
  LOCATION varchar,
  PRIMARY KEY ( CUSTOMER_ID )
  );

create table IF NOT EXISTS PRODUCT(
  PRODUCT_CODE varchar not null,
  COST numeric,
  STATUS varchar,
  PRIMARY KEY ( PRODUCT_CODE )
  );

create table IF NOT EXISTS TRANSACTION(
  TRANSACTION_ID int not null AUTO_INCREMENT,
  CUSTOMER_ID int not null,
  TRANSACTION_TIME DATE,
  QUANTITY int not null,
  PRODUCT_CODE varchar(80),
  PRIMARY KEY ( TRANSACTION_ID ),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
  FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT(PRODUCT_CODE)
);